UI adaptable to desktop version
emmanuelcortes2/ecp-portfolio pull request #5
Opened 2022-09-02 15:00 UTC by emmanuelcortes2

### Desktop version & responsiveness

- Add media queries to style.css so it displays correctly to different screen sizes.

2022-09-02 16:01 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @emmanuelcortes2 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🙌🤗

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice and Responsive Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 16:01 UTC, awais-amjed commented on index.html
> +                    <button class="p-button" type="button">See project</button>
Kindly update the button hover to show the text in white as shown in Figma design 😃

Your design:

![image](https://user-images.githubusercontent.com/73714615/188193398-69767da5-6f91-4246-b6de-93f48cac8abf.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188193537-43e7692f-b6cd-4793-8047-66d389e53c2d.png)

2022-09-02 20:16 UTC, vickymarz requested changes
Hi @emmanuelcortes2 , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 20:16 UTC, vickymarz commented on index.html
> +        <footer class="contact" id="contact">
- [ ] I think you kind of introduced an overflow in your contact section. Please adjust it to match the Figma design template chosen 👍🏽 

Your Design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188228144-267afc07-41df-4f35-a88f-75b9e0c21d57.png)

Figma Design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188228352-def84059-3987-4e4b-bb61-cc494c568791.png)

2022-09-02 20:16 UTC, vickymarz commented on index.html
> +                    <h1><strong>Tonic</strong></h1>
- [ ] As the previous reviewer suggested, kindly increase the font weight of all your project card heading to match the Figma design 🤗.

Your design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188228923-ed68d993-849f-4685-b293-6847e9bbeecc.png)

Figma design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188229056-cc7796ea-75c0-452a-902d-47205c451316.png)

2022-09-02 20:16 UTC, vickymarz commented on index.html
> +                <h1><strong>About<br>Myself</strong></h1>
- [ ] As the previous reviewer suggested, kindly increase the font weight of your **_` About Myself`_** heading to match the Figma design template you chose🤗 and also use the right color specified in the Figma design as your color is currently black.

Your design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188229322-aaa087cf-1f55-4c45-8004-2c726d9e87a2.png)

Figma design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/188229495-2a38a29d-b1e6-4509-bd32-b2f5399f6dc5.png)

2022-09-03 01:23 UTC, emmiiorji approved these changes
Hi @emmanuelcortes2, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/188250414-dcd8eb35-0c89-49cd-8f12-3db3e6ce3fb3.gif)


## Good Highlights ✅

- Implemented changes recommended
- Adherence to GitHub flow
- Descriptive PR
- Good commit messages

## Optional suggestions

- I recommend that you organize your images into a folder in order to reduce the cluttering of your project's home directory.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 13:11 UTC, merged